name: "Install Dashcam"
description: "Install Dashcam onto the runner. Must be done be the start action."
author: "TheBrowserCompany"

inputs:
  dashcam-version:
    description: "The version of Dashcam to install."
    default: "1.0.49"
    required: true
  node-version:
    description: "The version of Node.js to install."
    default: "16.20.2"
    required: true
  node-directory:
    description: "The directory to install Node.js to."
    default: "C:\nodejs16"
    required: true
  node-prefix:
    description: "The prefix to use for Node.js."
    default: "C:\nodejs16\npm-installs"
    required: true

runs:
  using: "composite"
  steps:
    # The Dashcam CLI talks to the running Dashcam GUI, so we need both
    - name: Install Dashcam GUI
      shell: pwsh
      run: |
        .\src\windows\dashcam-install\Install-DashcamGUI.ps1 `
          -DashcamVersion ${{ inputs.dashcam-version }}

    - name: Install Node.js for Dashcam CLI
      shell: pwsh
      run: |
        .\src\windows\dashcam-install\Install-NodeJS.ps1 `
          -Version ${{ inputs.node-version }} `
          -Directory ${{ inputs.node-directory }} `
          -Prefix ${{ inputs.node-prefix }}

    - name: Install Dashcam CLI
      shell: pwsh
      run: |
        $env:PATH = "${{ inputs.node-directory }};${{ inputs.node-prefix }};$env:PATH"
        .\src\windows\dashcam-install\Install-DashcamCLI.ps1
        Add-Content -Path $env:GITHUB_ENV -Encoding utf8 -Value "DASHCAM_NODE_DIR=${{ inputs.node-directory }}"

branding:
  icon: "download"
  color: "green"
