name: "Install Dashcam"
description: "Install Dashcam onto the runner. Must be done before the start action."
author: "TheBrowserCompany"

inputs:
  version:
    description: "The version of Dashcam to install. See releases here: https://github.com/replayableio/replayable/releases"
    required: true
  node-version:
    description: "The version of Node.js to install. Must match the required version for cli see: https://github.com/replayableio/cli/blob/main/package.json"
    required: true
  node-directory:
    description: "The directory to install Node.js to."
    required: true
  node-prefix:
    description: "The prefix to use for Node.js."
    required: true

runs:
  using: "composite"
  steps:
    # The Dashcam CLI talks to the running Dashcam GUI, so we need both
    - name: Install Dashcam GUI (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      env:
        DASHCAM_VERSION: ${{ inputs.version }}
      run: |
        $env:PATH = "$env:GITHUB_ACTION_PATH\src\windows;$env:PATH"
        Write-Host "Installing Dashcam GUI on ${{ runner.os }}"
        Install-DashcamGUI.ps1 -Version $env:DASHCAM_VERSION

    - name: Install Node.js for Dashcam CLI (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      env:
        NODE_VERSION: ${{ inputs.node-version }}
        NODE_DIRECTORY: ${{ inputs.node-directory }}
        NODE_PREFIX: ${{ inputs.node-prefix }}
      run: |
        Write-Host "Installing Node.js for Dashcam CLI on ${{ runner.os }}"

        $env:PATH = "$env:GITHUB_ACTION_PATH\src\windows;$env:PATH"
        Install-NodeJS.ps1 -Version $env:NODE_VERSION -Directory $env:NODE_DIRECTORY -Prefix $env:NODE_PREFIX

    - name: Install Dashcam CLI (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      env:
        NODE_DIRECTORY: ${{ inputs.node-directory }}
        NODE_PREFIX: ${{ inputs.node-prefix }}
      run: |
        Write-Host "Installing Dashcam CLI on ${{ runner.os }}"

        $env:PATH = "$env:GITHUB_ACTION_PATH\src\windows;$env:NODE_DIRECTORY;$env:NODE_PREFIX;$env:PATH"
        Install-DashcamCLI.ps1
        Add-Content -Path $env:GITHUB_ENV -Encoding utf8 -Value "DASHCAM_NODE_DIR=$env:NODE_DIRECTORY"

    - name: Install Dashcam GUI (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing Dashcam GUI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Node.js for Dashcam CLI (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing Node.js for Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam CLI (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam GUI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Dashcam GUI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Node.js for Dashcam CLI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Node.js for Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam CLI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

branding:
  icon: "download"
  color: "green"
