name: "Install Dashcam"
description: "Install Dashcam onto the runner. Must be done be the start action."
author: "TheBrowserCompany"

inputs:
  dashcam-version:
    description: "The version of Dashcam to install."
    default: "1.0.49"
    required: true
  node-version:
    description: "The version of Node.js to install."
    default: "16.20.2"
    required: true
  node-directory:
    description: "The directory to install Node.js to."
    default: "C:\nodejs16"
    required: true
  node-prefix:
    description: "The prefix to use for Node.js."
    default: "C:\nodejs16\npm-installs"
    required: true

runs:
  using: "composite"
  steps:
    # The Dashcam CLI talks to the running Dashcam GUI, so we need both
    - name: Install Dashcam GUI (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        Write-Output "Installing Dashcam GUI on ${{ runner.os }}"

        src\windows\Install-DashcamGUI.ps1 `
          -DashcamVersion ${{ inputs.dashcam-version }}

    - name: Install Node.js for Dashcam CLI (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        Write-Output "Installing Node.js for Dashcam CLI on ${{ runner.os }}"

        src\windows\Install-NodeJS.ps1 `
          -Version ${{ inputs.node-version }} `
          -Directory ${{ inputs.node-directory }} `
          -Prefix ${{ inputs.node-prefix }}

    - name: Install Dashcam CLI (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        Write-Output "Installing Dashcam CLI on ${{ runner.os }}"

        $env:PATH = "${{ inputs.node-directory }};${{ inputs.node-prefix }};$env:PATH"
        src\windows\Install-DashcamCLI.ps1
        Add-Content -Path $env:GITHUB_ENV -Encoding utf8 -Value "DASHCAM_NODE_DIR=${{ inputs.node-directory }}"

    - name: Install Dashcam GUI (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing Dashcam GUI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Node.js for Dashcam CLI (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing Node.js for Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam CLI (macOS)
      if: ${{ runner.os == 'macOS' }}
      shell: bash
      run: |
        echo "Installing Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam GUI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Dashcam GUI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Node.js for Dashcam CLI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Node.js for Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam CLI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

    - name: Install Dashcam CLI (Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Installing Dashcam CLI on ${{ runner.os }}"
        echo "Not supported yet"
        exit 1

branding:
  icon: "download"
  color: "green"
