name: "Stop the Dashcam CLI recording"
description: "Stops the Dashcam CLI recording"

runs:
  using: "composite"
  steps:
    - name: Stop Recording (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      env:
        TD_API_ROOT: https://api.testdriver.ai 
      run: |
        # Environment variable set by the dashcam-install action
        $env:PATH = "$env:DASHCAM_NODE_DIR;$env:DASHCAM_NODE_DIR\npm-installs;$env:PATH"
        dashcam stop --md >> $env:GITHUB_STEP_SUMMARY
