name: Pull Request - Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - '**/graphite-base/**'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Dashcam
        uses: ./.
        with:
          version: "1.0.49"
          cli-version: "0.8.3"
          node-version: "22.19.0"
          node-directory: "C:\\nodejs22"
          node-prefix: "C:\\nodejs22\\npm-installs"

      - name: Start Dashcam
        uses: ./start
        continue-on-error: true
        with:
          api-key: "1234567890"

      - name: Stop Dashcam
        uses: ./stop
        continue-on-error: true
        with:
          project-id: "507f1f77bcf86cd799439011"
