name: Pull Request - Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - '**/graphite-base/**'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Install Dashcam
        uses: ./.
    
      - name: Start Dashcam
        uses: ./start
        with:
          api-key: "1234567890"

      - name: Stop Dashcam
        uses: ./stop
        with:
          project-id: "507f1f77bcf86cd799439011"
