name: Pull Request - Validation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - '**/graphite-base/**'
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Log Environment
        shell: pwsh
        run: |
          Write-Host "Current path: $(Get-Location)"
          Write-Host "Current path: $(Get-Location -PSProvider FileSystem)"
          Get-ChildItem -Recurse -Force

      - name: Install Dashcam
        uses: testdriverai/action-dashcam@main
    
      - name: Start Dashcam
        uses: testdriverai/action-dashcam/start@main
        with:
          api-key: "1234567890"
    
      - name: Stop Dashcam
        uses: testdriverai/action-dashcam/stop@main
        with:
          project-id: "507f1f77bcf86cd799439011"
